### ISSUE TITLE
Pedagogical question: open-endedness?

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#11]
cc: @hugobowne @justinbois

I'm wrestling with one question right now: I really, really want to include one notebook which is very, very unstructured and open-ended. (This would probably be the last nb.) This simulates the scenario that most of us will be in when faced with a novel modelling question.

Yet, given that the class probably only will have had 2 hours with PyMC3, I'm also worried that this would be a bit "too much" for them.

Thus, I have the following hypothesis:

- Assume every notebook has an "instructor" version and a "student" version.
- Then, an unstructured notebook can be feasible IFF I make it clear to the students that "copying code (from the instructor version) and then mulling over it is a perfectly reasonable way to learn".
- Those who are competent won't have to refer to the instructor version.
- Those who are feeling less confident have the instructor version to fall back on, and can still learn.

Do you think this is a reasonable hypothesis? Would it be worthwhile to try this out during the tutorial?

**Comment by hugobowne** [comment]
@ericmjl I'm always up for such experiments. My concern is that there won't be enough time.

E.g. after set-up etc..., each of us will have around 110 minutes. If you give them 20 minutes to play around with the open-ended NB, they will have had only 90 minutes w/ PyMC3.

If you give them 30 minutes, etc...

The question is: what would this be replacing? I.e. what material will you _not_ cover in order to do this? Then we can check out the Bayes' factor.

**Comment by ericmjl** [comment]
Closing this issue; as I run through the tutorial overarching narrative, I'm seeing that this might not be as much of an issue.
