### ISSUE TITLE
Windows: conda installation problem

### ISSUE THREAD

**Issue by pllim** [ericmjl/bayesian-stats-modelling-tutorial#53]
I tried your conda instruction (`conda env create -f environment.yml -v`) and ran into this error:
```
pyc file failed to compile successfully (run_command failed)
python_exe_full_path: C:\...\envs\bayesian-modelling-tutorial\python.exe
py_full_path: C:\...\envs\bayesian-modelling-tutorial\Lib\site-packages\missingno\utils.py
pyc_full_path: C:\...\envs\bayesian-modelling-tutorial\Lib\site-packages\missingno\__pycache__\utils.cpython-37.pyc
compile rc: 1
compile stdout: "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"

compile stderr: ERROR: The system was unable to find the specified registry key or value.
```
The above message was repeated several times for some other packages, following by this at the end:
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\lib\site-packages\conda\core\link.py", line 558,in _execute
    cls._execute_post_link_actions(pkg_idx_tracked, axngroup)
  File "C:\...\lib\site-packages\conda\core\link.py", line 664,in _execute_post_link_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
running your command again with `-v` will provide additional information
location of failed script: C:\...\envs\bayesian-modelling-tutorial\Scripts\.qt-post-link.bat
```
I am using conda 4.6.14 on Windows 10, with Git Bash shell.

p.s. I also tried a combo of creating a basic conda env and then pip install some stuff into it (several variants of that combo) but even when I managed to start the notebook, the import step crashed the notebook kernel with DLL error.

**Comment by ericmjl** [comment]
Hmmmm. This one is definitely baffling for me. I'm going to have to rely on others who have more experience with Windows than I do, as I've been using Unix (macOS/Linux) systems exclusively since 2006.

Let's see if others who are participating in the tutorial have the same set of questions or not, or if @hugobowne might have a clue here.

If nothing can be resolved natively on your computer, the backup is to use the hosted Binder. Coding up the exercises is more important than getting it installed, which is why the hosted Binder notebooks exist. If you can get that experience, no matter how you get there, you'll be in a good place post-tutorial.

**Comment by pllim** [comment]
Re: Binder -- That needs internet, right? I am worried that WiFi might be sketchy at the conference venue. But if you think it can be reliably used, then I am okay with that option.

**Comment by pllim** [comment]
**Solution**

This fixed the installation problem, thanks to the help from @jhunkeler.

1. Remove the `ericmjl` channel from the YML.
2. From the Start menu, look for "developer command prompt for VS 2017" and start it (the year might be different depending on your VS installation).
3. In the dev cmd prompt, run the command to create env.
