### ISSUE TITLE
SciPy 2019 Prep

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#65]
Following up on the email thread.

- 1 hr on re-capping probability distribution stories & ECDFs.
- Then 3 hours starting from the coin flip to birds to arbitrary regression. That should be enough content. I will have to rewrite the PPL notebooks.

**Comment by hugobowne** [comment]
I can create NB for the 1st hour. 

I'd also happily do the intro. to Bayes + coin flip/CTR in PPL as it's all in NB 2. Then you can take it from current NB 3 onward?

**Comment by ericmjl** [comment]
> I can create NB for the 1st hour.

Does it need a new NB? AFAICS, the material is already in NB1.

> I'd also happily do the intro. to Bayes + coin flip/CTR in PPL as it's all in NB 2. 

Which of coin flip/CTR would you do? As it currently stands, it's a bit confusing to jump between coin flip and click-through rate. It's clearer to follow, I think, if we:

- Either start with coin flip and then add CTR (but this takes a while)
- Or just do one of them.

Personal preference is to do just one of them, and probably just biased coin flip, because the point isn't to introduce advertising modelling problems, the point is to introduce "here's how you do a classic Bayes' problem, inferring a proportion, using a PPL". Introducing CTR usually means spending more minutes on motivating an advertising problem and introduces just that more overhead. 

> Then you can take it from current NB 3 onward?

Yes. That said, I do think NB3 and on needs reworking. The last time we did it, I found there wasn't enough opportunity for people to code. Partly it's timing: participants need time to wrap their heads around a new problem. Partly it's how I set up the exercise: I need to place better prompts, and gradate the blanking out of code.

Leaving this example here below for myself:

First exercise template:

```python
with pm.Model() as model:
    # fill in distribution object and its parameters

    # define prior for `p`, for probability of heads/tails
    p = pm.________('p', ________)  
    # define likelihood for data
    like = pm._________('like', p=___________, n=____________, observed=____________)
```


Second exercise template:

```python
with ________________ as __________:
    # fill in distribution objects and their parameters

    # define prior for `p`, for probability of heads/tails
    p = pm.___________________________

    # define likelihood for data
    like = pm.___________________________
```

Third exercise template:

```python
with _______________________________:
    # implement model using PyMC3 distribution objects.
    
    # define prior for `p`, for probability of heads/tails

    # define likelihood for data
````

**Comment by hugobowne** [comment]
> Does it need a new NB? AFAICS, the material is already in NB1. 

There's also a lot of other material in NB1 that we won't use (e.g. all the hands-on for joint/conditional). The plan would be to get the timings down to  ~1 hour. We could leave that stuff in but I think the leaner experience is far better if the material in each NB is precise  w/out too much "OK, we'll skip this part now & you can read/code it if you like"

> Which of coin flip/CTR would you do? 

After introducing probability distributions and their stories,  the point is that these are the same! When introducing the stories, we'll actually see that CTR, coin flip, disease incidence are the same. Doing one **is** doing the other. I have a **strong** preference for not doing a coin flip when working through PPL. It's always good to ground pedagogy in real-world questions as learners are more invested  (and there aren't any biased coins :P). Because we'll first teach probability distributions and their stories, there won't be any cognitive overhead.

Wrt

> It's a bit confusing to jump between coin flip and click-through rate

no, it isn't once we see they're the same story!

**Comment by hugobowne** [comment]
scipy done!
